apiVersion: v1
kind: Pod
metadata:
  name: jupyterhub-kube
  labels:
    app.kubernetes.io/name: nvidia-cuda-jupyterhub
spec:
  containers:
  - name: jupyterhub-kube
    image: batrakunal/nvidia_cuda_jupyterhub:latest
    command: ["/bin/sh", "-c", "jupyterhub", "-f", "/opt/jupyterhub/jupyterhub_config.py"]
    ports:
    - containerPort: 8000
      name: http-port-8000
    - containerPort: 8888
      name: http-port-8888
    - containerPort: 22
      name: http-port-22
  #  volumeMounts:
  #  - mountPath: /home
  #    name: home
    volumeMounts:
    - mountPath: /opt
      name: opt 
  volumes:
  #- name: home
  #  hostPath:
  #    path: /home
  - name: opt
    hostPath:
      path: /data/docker/volumes/conda_all/_data 
        
#        volumeMounts:
#        - mountPath: /opt
#          name: my-pvc
#      volumes:
#        - name: nvidia_cuda_jupyterhub
#          persistentVolumeClaim:
#            ClaimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nvidia-cuda-jupyterhub
  ports:
  - port: 8000
    targetPort: 8000
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30005
    protocol: TCP
    name: http
  - port: 22
    targetPort: 22
    nodePort: 32222
    protocol: TCP
    name: ssh
  
